export const home=require('./api/home.routes')
export const login=require('./api/login.routes')
export const register=require('./api/register.routes')
export const videosPage=require('./api/videos/videosPage.routes')
export const uploadvideosPage=require('./api/videos/uploadvideosPage.routes')